### ISSUE TITLE
Suggestion (perhaps)

### ISSUE THREAD

**Issue by peter-budo** [hamsterready/android-accordion-view#1]
I'm not familiar with 

```
<dependency>
      <groupId>android</groupId>
      <artifactId>android</artifactId>
      <version>2.2_r3</version>
      <scope>provided</scope>
    </dependency>
```

and neither my IntelliJ like it it. You may want to replace it with more commonly used 

```
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>android</artifactId>
            <version>2.3.3</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by hamsterready** [comment]
Dependency group follows naming convention from https://github.com/mosabua/maven-android-sdk-deployer which I found very useful and up to date.

See details on mosabua project.

**Comment by peter-budo** [comment]
But this will mean that anyone who will try to participate in your project has to have Maven android sdk deployer. If so you better put that in README
